/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfUseRouteImport } from './routes/terms-of-use'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PublicDataRouteImport } from './routes/public-data'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as ProjectsRouteRouteImport } from './routes/projects/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as HelpAndSupportIndexRouteImport } from './routes/help-and-support/index'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'

const TermsOfUseRoute = TermsOfUseRouteImport.update({
  id: '/terms-of-use',
  path: '/terms-of-use',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicDataRoute = PublicDataRouteImport.update({
  id: '/public-data',
  path: '/public-data',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRouteRoute = ProjectsRouteRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRouteRoute,
} as any)
const HelpAndSupportIndexRoute = HelpAndSupportIndexRouteImport.update({
  id: '/help-and-support/',
  path: '/help-and-support/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRouteRouteWithChildren
  '/get-started': typeof GetStartedRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/public-data': typeof PublicDataRoute
  '/resources': typeof ResourcesRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/about/': typeof AboutIndexRoute
  '/help-and-support/': typeof HelpAndSupportIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/get-started': typeof GetStartedRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/public-data': typeof PublicDataRoute
  '/resources': typeof ResourcesRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/about': typeof AboutIndexRoute
  '/help-and-support': typeof HelpAndSupportIndexRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRouteRouteWithChildren
  '/get-started': typeof GetStartedRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/public-data': typeof PublicDataRoute
  '/resources': typeof ResourcesRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/about/': typeof AboutIndexRoute
  '/help-and-support/': typeof HelpAndSupportIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects'
    | '/get-started'
    | '/privacy-policy'
    | '/public-data'
    | '/resources'
    | '/terms-of-use'
    | '/projects/$projectId'
    | '/about/'
    | '/help-and-support/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/get-started'
    | '/privacy-policy'
    | '/public-data'
    | '/resources'
    | '/terms-of-use'
    | '/projects/$projectId'
    | '/about'
    | '/help-and-support'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/projects'
    | '/get-started'
    | '/privacy-policy'
    | '/public-data'
    | '/resources'
    | '/terms-of-use'
    | '/projects/$projectId'
    | '/about/'
    | '/help-and-support/'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsRouteRoute: typeof ProjectsRouteRouteWithChildren
  GetStartedRoute: typeof GetStartedRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  PublicDataRoute: typeof PublicDataRoute
  ResourcesRoute: typeof ResourcesRoute
  TermsOfUseRoute: typeof TermsOfUseRoute
  AboutIndexRoute: typeof AboutIndexRoute
  HelpAndSupportIndexRoute: typeof HelpAndSupportIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-use': {
      id: '/terms-of-use'
      path: '/terms-of-use'
      fullPath: '/terms-of-use'
      preLoaderRoute: typeof TermsOfUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-data': {
      id: '/public-data'
      path: '/public-data'
      fullPath: '/public-data'
      preLoaderRoute: typeof PublicDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRouteRoute
    }
    '/help-and-support/': {
      id: '/help-and-support/'
      path: '/help-and-support'
      fullPath: '/help-and-support/'
      preLoaderRoute: typeof HelpAndSupportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRouteRoute
    }
  }
}

interface ProjectsRouteRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteRouteChildren: ProjectsRouteRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteRouteWithChildren = ProjectsRouteRoute._addFileChildren(
  ProjectsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsRouteRoute: ProjectsRouteRouteWithChildren,
  GetStartedRoute: GetStartedRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  PublicDataRoute: PublicDataRoute,
  ResourcesRoute: ResourcesRoute,
  TermsOfUseRoute: TermsOfUseRoute,
  AboutIndexRoute: AboutIndexRoute,
  HelpAndSupportIndexRoute: HelpAndSupportIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
